### get all users
GET http://localhost:3000/users
Content-Type: application/json



### get all auths
GET http://localhost:3000/auth
Content-Type: application/json


### register 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"anto",
    "email":"anto5@gmail.com",
    "password":"123456"
}


### get user

GET http://localhost:3000/users/10
Content-Type: application/json




### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"anto5@gmail.com",
    "password":"123456"
}


### update
PUT http://localhost:3000/users/9
Content-Type: application/json

{
    "username":"antoni777o",
    "password":"12345467"
}

### delete
DELETE http://localhost:3000/users/18
Content-Type: application/json

{
    "password":"$2b$10$H/C0v2As.1ZuSOxsvaqane1chUXaJIZxokFBPkfjLNmvdN1CzQbZi"
}

### logout
DELETE  http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTcyMzg5OTI3NSwiZXhwIjoxNzIzOTAxMDc1fQ.8A158Fxz9f_s5SGxjGNRjncXePD3nxQVz8KTsJM1Ric


### clear table
DELETE http://localhost:3000/users
Content-Type: application/json