### get all users
GET http://localhost:3000/users
Content-Type: application/json


### register 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"anto",
    "email":"anto55@gmail.com",
    "password":"12345"
}


### get user

GET http://localhost:3000/users/10
Content-Type: application/json




### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"anto55@gmail.com",
    "password":"12345"
}


### update
PUT http://localhost:3000/users/9
Content-Type: application/json

{
    "username":"antoni777o",
    "password":"12345467"
}

### delete
DELETE http://localhost:3000/users/10
Content-Type: application/json

{
    "password":"$2b$10$H/C0v2As.1ZuSOxsvaqane1chUXaJIZxokFBPkfjLNmvdN1CzQbZi"
}

### delete all table
DELETE http://localhost:3000/users/delete
Content-Type: application/json